
<Box@MDBoxLayout>:
    id:boxcolor
    md_bg_color:app.theme_cls.primary_dark
    spacing:"3dp"
    padding:'2dp'


<Crd@MDCard>:  
    
<Lyt@MDRelativeLayout>:
   

<Btn1@MDRaisedButton>:
    
   
<Txt1@MDTextField>:
    id:txtin
    md_bg_color:app.theme_cls.primary_palette

<IBtn2@MDIconButton>:

<Lbl@MDLabel>:


<Loading_screen>:
   
    Box:
        orientation:'vertical'
        md_bg_color:"#2C4A4E"
        Lyt:
            Image:

                source: 'kali1.png'
                size_hint:None,None
                pos_hint: {'center_x': 0.5,'center_y': 0.85}
        
            MDSpinner:
                size_hint: None, None
                size: dp(46), dp(46)
                pos_hint: {'center_x': .5, 'center_y': .5}
            
            MDProgressBar:
                id:process_bar
                value: 0
                max: 100
                pos_hint: {'center_x': .5, 'center_y': .2}
                size_hint: .8, None
            